name: autoupdate
on:
  push: {}
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-22.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        continue-on-error: true
        env:
          GITHUB_TOKEN: "${{ secrets.DATAWAVE_BOT_BUILDER_TOKEN }}"
          DRY_RUN: "false"
          PR_FILTER: "protected"
          EXCLUDED_LABELS: "dependencies,no_update"
          PR_READY_STATE: "ready_for_review"
          MERGE_MSG: "Branch was auto-updated on change of target."
          RETRY_COUNT: "5"
          RETRY_SLEEP: "300"
          MERGE_CONFLICT_ACTION: "ignore"
          # See https://github.com/chinthakagodawita/autoupdate for option descriptions
   
